version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    cooldown:
      default-days: 1
    assignees:
      - alexey-max-fedorov
    commit-message:
      prefix: '[root]'
    ignore:
      - dependency-name: typescript
        update-types: ['version-update:semver-major']

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    assignees:
      - alexey-max-fedorov
    commit-message:
      prefix: '[github-actions]'
